<p>
<code><b><% if (nYear == 2004) { %>-<% } else { %>+<% } %></b></code>

<a href="efes2004.htm"><b>15th Efes Pilsener BF '04</b></a></p>

<% if (nYear == 2004) { %>
<ul>

<li><small><a href="sammcclain.htm">Mighty Sam McClain</a></small></li>

<li><small><a href="lcn.htm">Little Charlie &amp; The Nightcats</a></small></li>

<li><small><a href="frjack.htm">Fruteland Jackson</a></small></li>

</ul>
<% } %>



<p>
<code><b><% if (nYear == 2003) { %>-<% } else { %>+<% } %></b></code>

<a href="efes2003.htm"><b>14th Efes Pilsener BF '03</b></a></p>

<% if (nYear == 2003) { %>
<ul>

<li><small><a href="jerryricks.htm">&quot;Philadelphia&quot; Jerry Ricks</a></small></li>

<li><small><a href="wcclark.htm">W.C.Clark</a></small></li>

<li><small><a href="/bluesmen/WC_Clark">Интервью с W.C.Clark</a></small></li>

<li><small><a href="roomful.htm">Roomful Of Blues</a></small></li>

<li><small><a href="fedor2003.htm">О фестивале Efes Pilsener 2003</a></small></li>

<li><small><a href="quiz2003.htm">Конкурс blues.ru!</a></small></li>

<li><small><a href="quiz2003res.htm">Результаты конкурса</a></small></li>

</ul>
<% } %>




<p>
<code><b><% if (nYear == 2002) { %>-<% } else { %>+<% } %></b></code>

<a href="efes2002.htm">13th Efes Pilsener BF '02</a></p>

<% if (nYear == 2002) { %>
<ul>

<li><small><a href="loured.htm">Louisiana Red</a></small></li>

<li><small><a href="liled.htm">Lil 'Ed and the Blues Imperials</a></small></li>

<li><small><a href="cjchenier.htm">C.J.Chenier &amp; the Red Hot Louisiana Band</a></small></li>

</ul>
<% } %>


<p>
<code><b><% if (nYear == 2001) { %>-<% } else { %>+<% } %></b></code>

<a href="efes2001.htm">12th Efes Pilsener BF '01</a></p>

<% if (nYear == 2001) { %>
<ul>

<li><small><a href="contest2001.htm">Фестивальный конкурс!</a></small></li>

<li><small><a href="contres2001.htm">Результаты конкурса!</a></small></li>

<li><small><a href="before2001.htm">Сказано до открытия...</a></small></li>

<li><small><a href="eddyking.htm">Eddy "King" Milton</a></small></li>

<li><small><a href="o_taylor.htm">Otis Taylor</a></small></li>

<li><small><a href="michhill.htm">Michael Hill</a></small></li>

</ul>
<% } %>

<p>
<code><b><% if (nYear == 2000) { %>-<% } else { %>+<% } %></b></code>

<a href="efes2000.htm">11th Efes Pilsener BF '00</a></p>

<% if (nYear == 2000) {%>

<ul>

<li><small><a target="_blank" href="/bluesnews/00Autumn/00Efes.htm">
ВЭБ о фестивале</a></small></small></li>

<li><small><a href="longjohn.htm">Long John Hunter 
&amp; The Bad News Blues Band</a>
<ul>
<li><a target="_blank" href="/bluesnews/00Autumn/00Efes3.htm">ВЭБ о LJH</a></li>
<li><a target="_blank" href="/bluesnews/00Autumn/00EfesHunter.htm">интервью ВЭБ</a></li>
</ul>

</small></li>

<li><small><a href="holmesbr.htm">The Holmes Brothers</a>
<ul>
<li><a target="_blank" href="/bluesnews/00Autumn/00Efes1.htm">ВЭБ о HB</a></li>
<li><a target="_blank" href="/bluesnews/00Autumn/00EfesHolmes.htm">интервью ВЭБ</a></li>
</ul>
</small></li>

<li><small><a href="zydeco.htm">Lil' Brian &amp; The Zydeco Travellers</a>
<ul>
<li><a target="_blank" href="/bluesnews/00Autumn/00Efes2.htm">ВЭБ о LB &amp; ZT</a></li>
<li><a target="_blank" href="/bluesnews/00Autumn/00EfesBryan.htm">интервью ВЭБ</a></li>
</ul>
</small></li>

<li><small><a target="_blank" href="/bluesnews/00Autumn/00EfesJ.htm">Фоторепортаж с 
послефестивального джема</a>
</small></li>

<li><small><a target="_blank" href="/bluesnews/00Autumn/00EfesLot.htm">Конкурс 
blues.ru</a></small></li>

<li><small><a href="bluesru.htm">Blues.ru о фестивале</a></small></li>

</ul>

<% } %>

<p>
<code><b><% if (nYear == 1999) { %>-<% } else { %>+<% } %></b></code>

<a href="about1999.htm">10th Efes Pilsener BF '99</a></p>

<% if (nYear == 1999) { %>
<ul>

<li><small><a href="about1999.htm">
ВЭБ о фестивале</a></small></small></li>

<li><small><a href="clearwater.htm">Eddy "The Chief" Clearwater</a><br>
<ul><li><a href="eddyint.htm">интервью ВЭБ</a></li></ul>
</small></li>

<li><small><a href="bobbyrush.htm">Bobby Rush</a><br>
<ul><li><a href="rushint.htm">интервью ВЭБ</a></li></ul>
</small></li>

<li><small><a href="chrtking.htm">Chris Thomas King</a><br>
<ul><li><a href="kingint.htm">интервью ВЭБ</a></li></ul>
</small></li>

</ul>

<% } %>
<p><a href="history.htm">История фестиваля</a></p>

<p align="center"><small>28, 29 и 30 октября 2004,<br>
Москва, Лужники, УСЗ &laquo;Дружба&raquo;.</small></p>

<p align="center"><small>2 ноября 2004,<br>
Ростов-на-Дону, Дворец Спорта.</small></p>

<p align="center"><small>5 ноября 2004,<br>
Уфа, ГДК (Городской Дворец Культуры).</small></p>

<p align="center"><small>7 ноября 2004,<br>
Екатеринбург, ДИВС (Дворец игровых видов спорта).</small></p>

<p align="center"><small>9 ноября 2004,<br>
Санкт-Петербург, ДС &laquo;Юбилейный&raquo;.</small></p>

