<table border="2" cellpadding="2" cellspacing="2" width="100%">
  <tbody>
    <tr>
      <!-- Row 1 -->
      <td rowspan="2" width="33%"><center>
        <h2><em><a name="new">Глава I</a></em></h2>
        <p>1915-1931<br>
        Детство, отрочество</p>
                </center></td>
      <td>
        <dl>
          <dt><i><a href="/mojobook/mojo1-1.htm">часть I</a></i>:
          <dd>Родители и родственники. Дельта. Кларксдейл. Бабушка мисс Делла. Плантация Стоваллов standing at the crossroads.
          <dt><i><a href="/mojobook/Mojo1-2.htm">часть II</a></i>:
          <dd>Арендаторы-издольщики. Бабушкин дом. Прозвище. Музыка. Церковь. Вуду. Моджо.
          <dt><i><a href="/mojobook/mojo1-3.htm">часть III</a></i>:
          <dd>Друг детства Эдди Бойд. Аккордеон, варган, губная гармоника. Познание блюза и мечты о славе.</dd>
        </dl>
      </td>
    </tr>
  </tbody>
</table>
<table border="2" cellpadding="2" cellspacing="2" width="100%">
  <tbody>
    <tr>
      <!-- Row 1 -->
      <td rowspan="2" width="33%"><center>
        <h2><em>Глава II</em></h2>
        <p>1932-1943<br>
        От первой гитары<br>
        до первой записи.</p>
        <p>1941: <a href="http://media.blues.ru/mojobook/MM_CountryBl.rm">Country Blues</a><br>
        1941: <a href="http://media.blues.ru/mojobook/MM_IBeTroubled.rm">I Be's Troubled</a><br>
        1942: <a href="http://media.blues.ru/mojobook/Ramblin.rm">Ramblin'Kid Blues</a></p>
        </center></td>
      <td>
        <dl>
          <dt><i><a href="/mojobook/mojo2-1.htm">часть I</a></i>:
          <dd>Первые музыкальные заработки,
            первые гитары, техника &quot;слайд&quot;,
            Сон Хаус, свадьба, Чарли Пэттон,
            Роберт МакКой
          <dt><i><a href="/mojobook/Mojo2-2.htm">часть II</a></i>:
          <dd>Великая депрессия, сегрегация,
            Роберт Джонсон, семейные передряги,
            электроскрипка, кабачок и самогон,
            Алан Ломакс и первая запись
          <dt><i><a href="/mojobook/mojo2-3.htm">часть III</a></i>:
          <dd>&quot;Время Короля бисквитов&quot;, война,
            вторая запись для Библиотеки
            Конгресса США, семья и хозяйство,
            отъезд в Чикаго</dd>
        </dl>
      </td>
    </tr>
  </tbody>
</table>
<table border="2" cellpadding="2" cellspacing="2" width="100%">
  <tbody>
    <tr>
      <!-- Row 1 -->
      <td rowspan="2" width="33%"><center>
        <h2><em>Глава III</em></h2>
        <p>1943-1948<br>
        Приезд в Чикаго.<br>
        Мадди становится профессиональным
        музыкантом.</p>
        <p>1947: <a href="http://media.blues.ru/mojobook/MM_Gypsy.rm">Gypsy Woman</a><br>
        1948: <a href="http://media.blues.ru/mojobook/MM_CantBeSatisfied.rm">I Can't Be Satisfied</a></p>
        </center></td>
      <td>
        <dl>
          <dt><i><a href="/mojobook/Mojo3-1.htm">часть I</a></i>:
          <dd>Довоенный чикагский блюз. Биг Билл
            Брунзи. Джимми Роджерс
          <dt><i><a href="/mojobook/Mojo3-2.htm">часть II</a></i>:
          <dd>Максвэлл Стрит. Клод &quot;Блю Смитти&quot;
            Смит. <b>1946</b>г. - первые
            професиональные записи
          <dt><i><a href="/mojobook/Mojo3-3.htm">часть III</a></i>:
          <dd>Литл Уолтер. Саннилэнд Слим.
          <dt><i><a href="/mojobook/Mojo3-4.htm">часть IY</a></i>:
          <dd>Братья Чесс. Записи для &quot;Аристократа&quot;.
            Бо Диддли. Мгновенный успех &quot;I Can't Be
            Satisfied&quot;</dd>
        </dl>
      </td>
    </tr>
  </tbody>
</table>
<table border="2" cellpadding="2" cellspacing="2" width="100%">
  <tbody>
    <tr>
      <!-- Row 1 -->
      <td rowspan="2" width="33%"><center>
        <h2><em>Глава IV</em></h2>
        <p>1947-1955<br>
        Создание блюзбэнда</p>
        <p>1950: <a href="http://media.blues.ru/mojobook/MM_RollingStone.rm">Rolling Stone</a><br>
        1950: <a href="http://media.blues.ru/mojobook/MM_RollinTumblin.rm">Rollin' And Tumblin'</a><br>
        1953: <a href="http://media.blues.ru/mojobook/MM_BabyPleaseDontGo.rm">Baby, Please Don't Go</a></p>
        <p>Глава IV: <a href="/mojobook/MojoMan4.zip"><font size="-1"><i>zip file</i></font></a></p>
        </center></td>
      <td rowspan="2" width="67%">
        <dl>
          <dt><a href="/mojobook/Mojo4-1.htm"><i>часть I</i></a>:
          <dd>Чикагский блюз, электрическая
            гитара и инновации Мадди Уотерса.
            Мадди как лидер &quot;олл-старз&quot;-блюзбэнда.
            <b>1948</b>г. - Мадди женится.
          <dt><a href="/mojobook/Mojo4-2.htm"><i>часть II</i></a>:
          <dd><b>1949</b>г. - гастроли и радио-концерты
            в Хелене, Миссиссиппи. <b>1950</b>г. -
            &quot;Rolling And Tumbling&quot; и &quot;Rolling Stone&quot;.
            &quot;Aristocrat&quot; становится &quot;Chess&quot;
          <dt><a href="/mojobook/Mojo4-3.htm"><i>часть III</i></a>:
          <dd>Мадди Уотерс как автор. <b>1951</b>г. -
            первая запись с бэндом. Сподвижники:
            Литл Уолтер, Джуниор Уэллс, Биг
            Уолтер Хортон
          <dt><a href="/mojobook/Mojo4-4.htm"><i>часть IV</i></a>:
          <dd>1952г. - Отис Спэнн присоединяется. <b>1953</b>г.
            - ушедшего в армию Джуниора Уэллса
            сменяет Биг Уолтер Хортон. <b>1954</b>г. -
            Мадди покупает свою первую
            электрогитару со встроенным
            звукоснимателем.</dd>
        </dl>
      </td>
    </tr>
  </tbody>
</table>
