<table border="0" cellpadding="5" cellspacing="0" height="100%" width="100%">
  <tr height="100%">
    <td bgcolor="#000000" width="220" valign="top">
      <span class="left">
      <a href="."><img border="0" src="rgtlg2.jpg" width="220" height="232"></a>
      <blockquote>
        <p><b><a href=".">О группе</a></b><br>
        <b><a href="Troublemaker.htm">CD Troublemaker '03</a></b><br>
        <b><a href="HeavySteppin.htm">CD Heavy Steppin' '02</a></b><br>
        <b><a href="http://arsenic.blues.ru">Arsenic Blues (ENG)</a></b><br>
        <b><a href="music.htm">Музыка</a></b><br>
        <b><a href="interview.htm">Интервью</a></b><br>
        <b><a href="review.htm">Отзывы</a></b><br>
        <b><a href="news.htm">Новости</a></b><br>
        <b><a href="photo.htm">Фотоархив</a></b><br>
        <b><a href="gigs.htm">Концерты</a></b><br>
        <b><a href="GuestBook.asp">Гостевая книга</a></b><br>
        <b><a href="mailto:ragtime@blues.ru">E-mail</a></b><br>
        <b><a href="/">Блюз в России</a></b><br>
        <a href="mailto:m_m@rambler.ru">(c) Nalrock 2001.</a></p>
      </blockquote>
      </span>
    </td>
    <td valign="top" bgcolor="#FFFFFF">
      <img border="0" src="lgmrt.gif" width="482" height="52">
      <hr size="1">
