<table cellpadding="10" cellspacing="0" border="0" align="right">


<tr><td width="150" align="left">
<a href="/"><img src="/images/bluesru-logo.svg" width="120" height="120" border="0" 
                 hspace="10"></a>
</td></tr>

<tr><td width="150" align="left">
<a href="http://www.roadhouse.ru"><img src="/images/suppbyrh.gif" 
   alt="При поддержке клуба Дом у Дороги" border="0" hspace="10" ></a>
</td></tr>

<tr><td width="150">
<% Blues.Ru.Ads.AdPages.ShowBluesAd(Context, 1); %>
</td></tr>

</table>



