<hr size="1">

<p align="center"><font color="red"><big>В Москве прошли гастроли<br>
Vidar Busk &amp; His True Believers!</big></font></p>


<ul>
  <li><b><a href="/bluesmen/Vidar_Busk/MoscowTour.htm">Пресс-релиз к московским гастролям</a></b></li>
  <li><a href="/bluesmen/Vidar_Busk/Hero.htm"><b>Биографическая статья о Бюске</b></a></li>
  <li><b><a href="http://www.vidar-busk.no/fs_main.html">Официальный сайт Vidar Busk</a></b></li>
</ul>

<p align="center"><b>Фотографии с концертов Бюска:</b></p>
<ul>
<li><small><a href="/bluesnews/Busk/page_01.htm">25 мая, суббота, Эхо Москвы &amp; концерт в Форте - часть I</a>.</small></li>
<li><small><a href="/bluesnews/Busk/page_02.htm">25 мая, суббота, концерт в Форте</a>.</small></li>
<li><small><a href="/bluesnews/Busk/page_03.htm">26 мая, воскресенье, концерт в ЛеКлубе</a>.</small></li>
<li><small><a href="/bluesnews/Busk/vb_bbk.htm">27 мая, понедельник, концерт в БиБиКинге</a>.</small></li>
</ul>


