#!/usr/bin/env python3
"""
Generate _redirects file for Cloudflare Pages.

Legacy URL patterns on blues.ru:
  /data/albumview.aspx?cdid=N  → /review/{slug}/
  /data/artistview.aspx?aid=N  → /artist/{legacy_dir}/

Cloudflare Pages _redirects supports one-line-per-URL query string matching
using the format: /path?param=value  /target  301
We generate one line per album/artist ID.

Also generates:
  albumview-redirects.csv  — Cloudflare bulk redirect CSV (same data)
  artistview-redirects.csv — Cloudflare bulk redirect CSV (same data)
  cloudflare-rules.txt     — notes for transforms that need dashboard config

Run from /Users/fedor/bluesru/
"""

import yaml
import re
from pathlib import Path

import os
ARC = Path(__file__).resolve().parent.parent
DATA = ARC / "data"
ALBUMS_DIR = DATA / "albums"
ARTISTS_YAML = DATA / "artists.yaml"
REVIEWS_DIR = DATA / "blues-data" / "reviews"  # unused, kept for fallback
OUT_REDIRECTS = ARC / "_redirects"
OUT_CF_NOTES = ARC / "cloudflare-rules.txt"


def load_albums():
    """Return dict: album_id → album dict."""
    albums = {}
    for p in ALBUMS_DIR.glob("*/*.yaml"):
        a = yaml.safe_load(p.read_text(encoding="utf-8"))
        if a and a.get("id"):
            albums[int(a["id"])] = a
    return albums


def load_review_by_album():
    """Return dict: album_id → review_slug (from embedded reviews in album YAMLs)."""
    review_by_album = {}
    for p in sorted(ALBUMS_DIR.glob("*/*.yaml")):
        album = yaml.safe_load(p.read_text(encoding="utf-8")) or {}
        album_id = album.get("id")
        reviews = album.get("reviews", [])
        if album_id and reviews:
            first_id = reviews[0].get("id", "")
            slug = f"review-{first_id}" if first_id else p.stem
            try:
                review_by_album[int(album_id)] = slug
            except (ValueError, TypeError):
                pass
    # Fallback to old separate review .md files
    if not review_by_album and REVIEWS_DIR.exists():
        for p in sorted(REVIEWS_DIR.glob("review-*.md")):
            text = p.read_text(encoding="utf-8")
            lines = text.split("\n")
            if not lines or lines[0].strip() != "---":
                continue
            meta = {}
            for line in lines[1:]:
                if line.strip() == "---":
                    break
                if ":" in line:
                    k, v = line.split(":", 1)
                    meta[k.strip()] = v.strip().strip("'\"")
            album_id_str = meta.get("album_id", "")
            slug = meta.get("slug", "")
            if album_id_str and slug:
                try:
                    review_by_album[int(album_id_str)] = slug
                except ValueError:
                    pass
    return review_by_album


def load_artists():
    """Return dict: artist_id → artist dict."""
    with open(ARTISTS_YAML, encoding="utf-8") as f:
        artists_list = yaml.safe_load(f)
    return {int(a["id"]): a for a in artists_list}


def legacy_dir_for_artist(artist):
    """Return the legacy bluesmen/ directory name, or '' if none."""
    lp = (artist.get("legacy_path") or "").strip("/")
    parts = lp.split("/")
    ld = parts[-1] if (parts and parts[-1]) else ""
    # Reject external URLs and entries with dots (domain names)
    if "." in ld or ld.startswith("www."):
        return ""
    return ld


def main():
    print("Generating _redirects...")

    albums = load_albums()
    review_by_album = load_review_by_album()
    artists = load_artists()
    lines = []
    lines.append("# Blues.Ru archive _redirects")
    lines.append("# Generated by generate_redirects.py")
    lines.append("")

    # ── Static ASPX page redirects ────────────────────────────────────────────
    lines.append("# Static ASPX page redirects")
    simple_redirects = [
        ("/review/default.aspx", "/review/"),
        ("/review/rss.aspx", "/review/rss.xml"),
        ("/news/default.aspx", "/news/"),
        ("/artist/default.aspx", "/artist/"),
        ("/forum/default.aspx", "/forum/"),
        ("/links/default.aspx", "/links/"),
        ("/club/default.aspx", "/club/"),
        ("/club/team.aspx", "/club/team/"),
        ("/club/tours.aspx", "/club/tours/"),
        ("/calendar/default.aspx", "/calendar/"),
        ("/data/varalbumsview.aspx", "/review/"),
    ]
    for old, new in simple_redirects:
        lines.append(f"{old}  {new}  301")

    # ── Efes section: .asp → .htm redirects ──────────────────────────────────
    lines.append("")
    lines.append("# /efes/*.asp → /efes/*.htm  (server exposed .asp URLs for .htm files)")
    efes_dir = ARC / "content" / "efes"
    if efes_dir.exists():
        for htm in sorted(efes_dir.glob("*.htm")):
            stem = htm.stem
            lines.append(f"/efes/{stem}.asp  /efes/{stem}.htm  301")

    lines.append("")

    # ── albumview.aspx?cdid=N → /artist/{artist}/{album}/ ────────────────────
    # Reviews now live under /artist/{artist-slug}/{album-slug}/
    lines.append("# /data/albumview.aspx?cdid=N → /artist/{artist}/{album}/  (one line per album ID)")
    album_redirects = []
    album_fallbacks = []

    def artist_url_slug(artist_obj):
        """Derive URL slug for artist (used in /artist/ path)."""
        if not artist_obj:
            return 'various-musicians'
        s = artist_obj.get('slug', '')
        if s:
            return s
        lp = artist_obj.get('legacy_path', '').strip('/')
        parts = lp.split('/')
        ld = parts[-1] if parts and parts[-1] else ''
        if ld and '.' not in ld and not ld.startswith('www.'):
            return re.sub(r'[^a-z0-9]+', '-', ld.lower()).strip('-')
        return 'various-musicians'

    for album_id in sorted(albums.keys()):
        album = albums[album_id]
        review_slug = review_by_album.get(album_id)
        album_slug = album.get('slug', '')
        artist_id = album.get('artist_id')
        artist_obj = artists.get(int(artist_id)) if artist_id else None
        a_slug = artist_url_slug(artist_obj)

        if review_slug and album_slug:
            # Strip "{a_slug}-" prefix from album URL segment
            url_album_slug = album_slug
            if a_slug not in ('various-musicians',) and url_album_slug.startswith(a_slug + '-'):
                url_album_slug = url_album_slug[len(a_slug) + 1:]
            src = f"/data/albumview.aspx?cdid={album_id}"
            tgt = f"/artist/{a_slug}/{url_album_slug}/"
            lines.append(f"{src}  {tgt}  301")
            album_redirects.append((album_id, tgt))
        else:
            album_fallbacks.append(album_id)

    if album_fallbacks:
        lines.append(f"# {len(album_fallbacks)} albums with no review → generic /review/ fallback (below)")
        for album_id in album_fallbacks:
            lines.append(f"/data/albumview.aspx?cdid={album_id}  /review/  302")

    lines.append("")

    # ── artistview.aspx?aid=N → /artist/{slug}/ ─────────────────────────────
    lines.append("# /data/artistview.aspx?aid=N → /artist/{slug}/  (one line per artist ID)")
    artist_redirects = []
    artist_fallbacks = []
    for artist_id in sorted(artists.keys()):
        artist = artists[artist_id]
        slug = artist.get("slug", "")
        legacy_dir = legacy_dir_for_artist(artist)
        # Always use slug if available; fall back to legacy_dir for orphans
        if slug:
            tgt = f"/artist/{slug}/"
        elif legacy_dir:
            tgt = f"/artist/{legacy_dir}/"
        else:
            tgt = "/artist/"
        src = f"/data/artistview.aspx?aid={artist_id}"
        if tgt != "/artist/":
            lines.append(f"{src}  {tgt}  301")
            artist_redirects.append((artist_id, tgt))
        else:
            artist_fallbacks.append(artist_id)

    if artist_fallbacks:
        lines.append(f"# {len(artist_fallbacks)} artists with no page → /artist/ fallback")
        for artist_id in artist_fallbacks:
            lines.append(f"/data/artistview.aspx?aid={artist_id}  /artist/  302")

    lines.append("")

    # ── /bluesmen/ → /artist/ (legacy URL rename) ────────────────────────────
    lines.append("# /bluesmen/ section renamed to /artist/")
    lines.append("/bluesmen/  /artist/  301")
    lines.append("/bluesmen/default.aspx  /artist/  301")
    # Per-artist: /bluesmen/Albert_Collins/ → /artist/albert-collins/
    lines.append("# Per-artist /bluesmen/OldDir/ → /artist/{slug}/")
    for artist_id in sorted(artists.keys()):
        artist = artists[artist_id]
        slug = artist.get("slug", "")
        legacy_dir = legacy_dir_for_artist(artist)
        if legacy_dir and slug and legacy_dir != slug:
            lines.append(f"/bluesmen/{legacy_dir}/  /artist/{slug}/  301")
            lines.append(f"/bluesmen/{legacy_dir}/*  /artist/{slug}/:splat  301")
    # Catch-all for any remaining /bluesmen/ paths
    lines.append("/bluesmen/*  /artist/:splat  301")
    lines.append("")

    # ── news.aspx?y=YYYY → /updates/YYYY/ ────────────────────────────────────
    lines.append("# news.aspx?y=YYYY → /updates/YYYY/")
    for year in range(2000, 2025):
        lines.append(f"/news.aspx?y={year}  /updates/{year}/  301")
    lines.append("/news.aspx  /updates/  301")
    lines.append("")

    # ── Catch-all for any remaining .aspx URLs ────────────────────────────────
    lines.append("# Catch-all for .aspx files not handled above")
    lines.append("/data/*  /  302")
    lines.append("/*.aspx  /  302")
    lines.append("")

    # ── Old section redirects ─────────────────────────────────────────────────
    lines.append("# Old section redirects")
    lines.append("/cdreview/  /review/  301")
    lines.append("/cdreview/*  /review/:splat  301")
    lines.append("/bluesme/*  /artist/:splat  301")
    lines.append("/zappazuhoi/default.htm  /zappazuhoi/  301")
    lines.append("")
    lines.append("# Old uppercase artist dir redirects")
    for old_dir, new_slug in [
        ("Blind_Boy_Fuller", "blind-boy-fuller"),
        ("Johnny_Winter", "johnny-winter"),
        ("Luther_Allison", "luther-allison"),
    ]:
        lines.append(f"/artist/{old_dir}/  /artist/{new_slug}/  301")
        lines.append(f"/artist/{old_dir}/*  /artist/{new_slug}/:splat  301")
    lines.append("")
    lines.append("# Gallery per-photo HTM pages → parent gallery index")
    lines.append("# Old gallery tools generated one .htm per photo; replaced by generated index.html")
    lines.append("/bluesnews/*/*.htm  /bluesnews/*/  301")
    lines.append("/bluesnews/*/*/*.htm  /bluesnews/*/*/  301")
    lines.append("/bluesnews/*/*/*/*.htm  /bluesnews/*/*/*/  301")
    lines.append("")

    OUT_REDIRECTS.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  _redirects: {len(lines)} lines ({len(album_redirects)} album + {len(artist_redirects)} artist)")

    # ── Cloudflare notes ──────────────────────────────────────────────────────
    cf_notes = """\
# Cloudflare Pages redirect notes
# The _redirects file contains all albumview and artistview redirects
# using query-string matching (one line per ID).
#
# Cloudflare Pages supports ?param=value matching in _redirects since 2023.
# If this does not work on your plan, use Cloudflare Bulk Redirect Lists:
#   - Import albumview-redirects.csv for albumview.aspx?cdid=N redirects
#   - Import artistview-redirects.csv for artistview.aspx?aid=N redirects
#
# /forum/?tid=N → /forum/topic-N/ is handled by serve.py locally.
# In production, set up a Cloudflare Transform Rule:
#   Match: URI path = /forum/ AND query string contains tid
#   Action: Redirect to /forum/topic-{tid}.html
"""
    OUT_CF_NOTES.write_text(cf_notes, encoding="utf-8")

    # ── Bulk redirect CSV files ───────────────────────────────────────────────
    base = "https://blues.ru"

    csv_lines = ["source_url,target_url,status_code,preserve_query_string"]
    for album_id in sorted(albums.keys()):
        review_slug = review_by_album.get(album_id)
        if review_slug:
            target = f"{base}/review/{review_slug}/"
        else:
            target = f"{base}/review/"
        csv_lines.append(f"{base}/data/albumview.aspx?cdid={album_id},{target},301,false")
    csv_path = ARC / "albumview-redirects.csv"
    csv_path.write_text("\n".join(csv_lines) + "\n", encoding="utf-8")
    print(f"  albumview-redirects.csv: {len(csv_lines)-1} entries")

    csv2_lines = ["source_url,target_url,status_code,preserve_query_string"]
    for artist_id in sorted(artists.keys()):
        artist = artists[artist_id]
        slug = artist.get("slug", "")
        legacy_dir = legacy_dir_for_artist(artist)
        if slug:
            target = f"{base}/artist/{slug}/"
        elif legacy_dir:
            target = f"{base}/artist/{legacy_dir}/"
        else:
            target = f"{base}/artist/"
        csv2_lines.append(f"{base}/data/artistview.aspx?aid={artist_id},{target},301,false")
    csv2_path = ARC / "artistview-redirects.csv"
    csv2_path.write_text("\n".join(csv2_lines) + "\n", encoding="utf-8")
    print(f"  artistview-redirects.csv: {len(csv2_lines)-1} entries")

    print("  cloudflare-rules.txt: notes written")


if __name__ == "__main__":
    main()
