#!/usr/bin/env python3
"""
Generate _redirects file for Cloudflare Pages.

Legacy URL patterns on blues.ru:
  /data/albumview.aspx?cdid=N  → /review/{slug}/
  /data/artistview.aspx?aid=N  → /artist/{legacy_dir}/

Cloudflare Pages _redirects supports one-line-per-URL query string matching
using the format: /path?param=value  /target  301
We generate one line per album/artist ID.

Also generates:
  albumview-redirects.csv  — Cloudflare bulk redirect CSV (same data)
  artistview-redirects.csv — Cloudflare bulk redirect CSV (same data)
  cloudflare-rules.txt     — notes for transforms that need dashboard config

Run from /Users/fedor/bluesru/
"""

import yaml
import re
from pathlib import Path

import os
ARC = Path(__file__).resolve().parent.parent
DATA = ARC / "data"
ALBUMS_DIR = DATA / "albums"
ARTISTS_YAML = DATA / "artists.yaml"
REVIEWS_DIR = DATA / "blues-data" / "reviews"  # unused, kept for fallback
OUT_REDIRECTS = ARC / "_redirects"
OUT_CF_NOTES = ARC / "cloudflare-rules.txt"


def load_albums():
    """Return dict: album_id → album dict."""
    albums = {}
    for p in ALBUMS_DIR.glob("*/*.yaml"):
        a = yaml.safe_load(p.read_text(encoding="utf-8"))
        if a and a.get("id"):
            albums[int(a["id"])] = a
    return albums


def load_review_by_album():
    """Return dict: album_id → review_slug (from embedded reviews in album YAMLs)."""
    review_by_album = {}
    for p in sorted(ALBUMS_DIR.glob("*/*.yaml")):
        album = yaml.safe_load(p.read_text(encoding="utf-8")) or {}
        album_id = album.get("id")
        reviews = album.get("reviews", [])
        if album_id and reviews:
            first_id = reviews[0].get("id", "")
            slug = f"review-{first_id}" if first_id else p.stem
            try:
                review_by_album[int(album_id)] = slug
            except (ValueError, TypeError):
                pass
    # Fallback to old separate review .md files
    if not review_by_album and REVIEWS_DIR.exists():
        for p in sorted(REVIEWS_DIR.glob("review-*.md")):
            text = p.read_text(encoding="utf-8")
            lines = text.split("\n")
            if not lines or lines[0].strip() != "---":
                continue
            meta = {}
            for line in lines[1:]:
                if line.strip() == "---":
                    break
                if ":" in line:
                    k, v = line.split(":", 1)
                    meta[k.strip()] = v.strip().strip("'\"")
            album_id_str = meta.get("album_id", "")
            slug = meta.get("slug", "")
            if album_id_str and slug:
                try:
                    review_by_album[int(album_id_str)] = slug
                except ValueError:
                    pass
    return review_by_album


def load_artists():
    """Return dict: artist_id → artist dict."""
    with open(ARTISTS_YAML, encoding="utf-8") as f:
        artists_list = yaml.safe_load(f)
    return {int(a["id"]): a for a in artists_list}


def legacy_dir_for_artist(artist):
    """Return the legacy bluesmen/ directory name, or '' if none."""
    lp = (artist.get("legacy_path") or "").strip("/")
    parts = lp.split("/")
    ld = parts[-1] if (parts and parts[-1]) else ""
    # Reject external URLs and entries with dots (domain names)
    if "." in ld or ld.startswith("www."):
        return ""
    return ld


def main():
    print("Generating _redirects...")

    albums = load_albums()
    review_by_album = load_review_by_album()
    artists = load_artists()
    lines = []
    lines.append("# Blues.Ru archive _redirects")
    lines.append("# Generated by generate_redirects.py")
    lines.append("")

    # ── Static ASPX page redirects ────────────────────────────────────────────
    lines.append("# Static ASPX page redirects")
    simple_redirects = [
        ("/review/default.aspx", "/review/"),
        ("/review/rss.aspx", "/review/rss.xml"),
        ("/news/default.aspx", "/news/"),
        ("/artist/default.aspx", "/artist/"),
        ("/forum/default.aspx", "/forum/"),
        ("/links/default.aspx", "/links/"),
        ("/club/default.aspx", "/club/"),
        ("/club/team.aspx", "/club/team/"),
        ("/club/tours.aspx", "/club/tours/"),
        ("/calendar/default.aspx", "/calendar/"),
        ("/data/varalbumsview.aspx", "/review/"),
    ]
    for old, new in simple_redirects:
        lines.append(f"{old}  {new}  301")

    # ── Efes section: .asp → .htm redirects ──────────────────────────────────
    lines.append("")
    lines.append("# /efes/*.asp → /efes/*.htm  (server exposed .asp URLs for .htm files)")
    efes_dir = ARC / "content" / "efes"
    if efes_dir.exists():
        for htm in sorted(efes_dir.glob("*.htm")):
            stem = htm.stem
            lines.append(f"/efes/{stem}.asp  /efes/{stem}.htm  301")

    lines.append("")

    # NOTE: /data/albumview.aspx?cdid=N and /data/artistview.aspx?aid=N redirects
    # are NOT in _redirects — CF Pages ignores query strings in _redirects rules.
    # These are handled by _middleware.js using /data/redirects.json (generated
    # at build time by generate_data_json.py).
    lines.append("# albumview.aspx / artistview.aspx → handled by _middleware.js (query-string)")
    lines.append("/data/albumview.aspx  /review/  302")
    lines.append("/data/artistview.aspx  /artist/  302")
    lines.append("")
    album_redirects = []
    artist_redirects = []

    # ── /bluesmen/ → /artist/ (legacy URL rename) ────────────────────────────
    # NOTE: Per-artist /bluesmen/OldDir/* dynamic rules are handled by _middleware.js.
    # Only the root and catch-all go here to stay under CF's 100 dynamic rule limit.
    lines.append("# /bluesmen/ section renamed to /artist/")
    lines.append("/bluesmen/  /artist/  301")
    lines.append("/bluesmen/default.aspx  /artist/  301")
    lines.append("# Catch-all for /bluesmen/ (per-artist slug mapping done in _middleware.js)")
    lines.append("/bluesmen/*  /artist/:splat  301")
    lines.append("")

    # ── news.aspx → /updates/ ────────────────────────────────────────────────
    # NOTE: news.aspx?y=YYYY query-string redirects handled by _middleware.js
    lines.append("# news.aspx (query-string redirect handled by middleware)")
    lines.append("/news.aspx  /updates/  301")
    lines.append("")

    # ── Catch-all for any remaining .aspx URLs ────────────────────────────────
    lines.append("# Catch-all for .aspx files not handled above")
    lines.append("/data/*  /  302")
    lines.append("/*.aspx  /  302")
    lines.append("")

    # ── Old section redirects ─────────────────────────────────────────────────
    lines.append("# Old section redirects")
    lines.append("/cdreview/  /review/  301")
    lines.append("/cdreview/*  /review/:splat  301")
    lines.append("/bluesme/*  /artist/:splat  301")
    lines.append("/zappazuhoi/default.htm  /zappazuhoi/  301")
    lines.append("")
    # Artists whose bluesmen/ TitleCase dirs are NOT in legacy_path → auto-gen misses them
    lines.append("# /bluesmen/ TitleCase dirs not in legacy_path (no auto-gen redirect)")
    for old_dir, new_slug in [
        ("Johnny_Winter", "johnny-winter"),
        ("Larry_McCray", "larry-mccray"),
        ("Lazy_Bill_Lucas", "lazy-bill-lucas"),
        ("Little_Richard", "little-richard"),
        ("Luther_Allison", "luther-allison"),   # legacy_path is Allison_Luther, different
        ("Scott_Henderson", "scott-henderson"),
    ]:
        lines.append(f"/bluesmen/{old_dir}/  /artist/{new_slug}/  301")
        lines.append(f"/bluesmen/{old_dir}/*  /artist/{new_slug}/:splat  301")
    # Artist whose slug differs from what the live site generates from the name
    lines.append("/artist/b-b-the-blues-shacks/  /artist/bb-the-blues-shacks/  301")
    lines.append("/artist/b-b-the-blues-shacks/*  /artist/bb-the-blues-shacks/:splat  301")
    lines.append("")
    lines.append("# /label/ TitleCase → lowercase (live site used TitleCase dirs)")
    lines.append("# /reading/ → /article/ (content consolidated into article/)")
    lines.append("/reading/  /article/  301")
    lines.append("/reading/wolf_palmer1.htm  /article/howling-wolf-deep-blues-1.html  301")
    lines.append("/reading/wolf_palmer2.htm  /article/howling-wolf-deep-blues-2.html  301")
    lines.append("/reading/RP01.htm  /article/robert-palmer-muddy-waters.html  301")
    lines.append("/reading/MuddyGordon1.htm  /article/muddy-waters-library-of-congress.html  301")
    lines.append("/reading/LB10/Living_blues.htm  /article/living-blues-veterans.html  301")
    lines.append("/reading/*  /article/  302")
    lines.append("")
    lines.append("# /label/ TitleCase → lowercase (live site used TitleCase dirs)")
    lines.append("/label/Alligator/  /label/alligator/  301")
    lines.append("/label/Alligator/*  /label/alligator/:splat  301")
    lines.append("/label/Blues_Leaf/  /label/blues-leaf/  301")
    lines.append("/label/Blues_Leaf/*  /label/blues-leaf/:splat  301")
    lines.append("/label/Chess/  /label/chess/  301")
    lines.append("/label/Chess/*  /label/chess/:splat  301")
    lines.append("")
    lines.append("# News archive redirects")
    lines.append("/news/archive/:year/  /news/:year/  301")
    lines.append("/news/archive/  /news/2024/  301")
    lines.append("")
    # ── bluesnews _13–_22 subdir → photo gallery redirects ───────────────────
    # Matched by JPG filename overlap; _12A has no registered galleries yet.
    lines.append("# bluesnews/_NN/subdir → /photo/ gallery redirects (matched by JPG filenames)")
    bluesnews_redirects = [
        ("/bluesnews/_13/13_02_16_Pardo/", "/photo/2013/2013-02-16-pardo/"),
        ("/bluesnews/_13/13_02_26_Rusinov_Oleinikova/", "/photo/2013/2013-02-26-rusinov-oleinikova/"),
        ("/bluesnews/_13/13_06_02_Hugh_Laurie/", "/photo/2013/2013-06-02-hugh-laurie-moscow/"),
        ("/bluesnews/_13/13_10_19_Arsen/", "/photo/2013/2013-10-19-arsen/"),
        ("/bluesnews/_13/13_10_19_Jimmy_Burns/", "/photo/2013/2013-10-19-jimmy-burns/"),
        ("/bluesnews/_13/13_11_08_Mishouris/", "/photo/2013/2013-11-08-mishouris/"),
        ("/bluesnews/_13/13_11_29_Joakim Tinderholt/", "/photo/2013/2013-11-29-joakim-tinderholt/"),
        ("/bluesnews/_14/14_03_10_Mishouris_Seals/", "/photo/2014/2014-03-10-mishouris-seals/"),
        ("/bluesnews/_14/14_04_19_Lisikova/", "/photo/2014/2014-04-19-lisikova/"),
        ("/bluesnews/_14/14_04_25_BB/", "/photo/2014/2014-04-25-bb/"),
        ("/bluesnews/_14/14_05_09_danny_giles/", "/photo/2014/2014-05-09-danny-giles/"),
        ("/bluesnews/_15/15_10_07_Dzagnidze/", "/photo/2015/2015-10-07-dzagnidze/"),
        ("/bluesnews/_15/15_10_30_KW2/", "/photo/2015/2015-10-30-kw2/"),
        ("/bluesnews/_15/15_11_21_Old_Fassion/", "/photo/2015/2015-11-21-old-fassion/"),
        ("/bluesnews/_15/16_09_30_SOBO/", "/photo/2016/2016-09-30-sobo/"),
        ("/bluesnews/_16/16_06_10_Eddie Shaw/", "/photo/2016/2016-06-10-eddie-shaw/"),
        ("/bluesnews/_16/16_06_10_Jam/", "/photo/2016/2016-06-10-jam/"),
        ("/bluesnews/_16/16_06_10_Lil_Ed/", "/photo/2016/2016-06-10-lil-ed-williams-siegel/"),
        ("/bluesnews/_16/16_06_10_TC_TC/", "/photo/2016/2016-06-10-tc-tc/"),
        ("/bluesnews/_16/16_06_12_Clearwater/", "/photo/2016/2016-06-12-clearwater/"),
        ("/bluesnews/_16/16_06_12_Migration/", "/photo/2016/2016-06-12-migration/"),
        ("/bluesnews/_16/16_07_07RWIP/", "/photo/2016/2016-07-07-raphael-wressnig-igor-prado/"),
        ("/bluesnews/_16/16_07_07_Raphael Wressnig Igor Prado/", "/photo/2016/2016-07-07-raphael-wressnig-igor-prado/"),
        ("/bluesnews/_16/16_11_02_ Giles_Robson/", "/photo/2016/2016-11-02-giles-robson/"),
        ("/bluesnews/_16/16_11_05_Kozh_Jhuk/", "/photo/2016/2016-11-05-kozh-jhuk/"),
        ("/bluesnews/_16/16_12_10_Smith/", "/photo/2016/2016-12-10-jc-smith/"),
        ("/bluesnews/_16/19_06_11_Weskey/", "/photo/2019/2019-06-11-weskey/"),
        ("/bluesnews/_17/17_01_21_Tomi_Leino/", "/photo/2017/2017-01-21-tomi-leino/"),
        ("/bluesnews/_17/17_01_28_Chino/", "/photo/2017/2017-01-28-chino-swingslide/"),
        ("/bluesnews/_17/17_06_03_Shanna_Waterstown/", "/photo/2017/2017-06-03-shanna-waterstown/"),
        ("/bluesnews/_17/17_10_23_Tarasov/", "/photo/2017/2017-10-23-tarasov/"),
        ("/bluesnews/_17/17_10_25_Ash/", "/photo/2017/2017-10-25-frank-ash/"),
        ("/bluesnews/_17/17_10_28_JCSmith/", "/photo/2017/2017-10-28-jcsmith/"),
        ("/bluesnews/_17/17_11_13_ChrisRea/", "/photo/2017/2017-11-13-chris-rea-moscow/"),
        ("/bluesnews/_17/17_11_30_Kaverkin/", "/photo/2017/2017-11-30-kaverkin/"),
        ("/bluesnews/_17/17_11_30_folkline/", "/photo/2017/2017-11-30-folkline/"),
        ("/bluesnews/_17/Iv_Sh/", "/photo/2017/2017-iv-sh/"),
        ("/bluesnews/_17/Waterstown_Delta/", "/photo/2017/2017-waterstown-delta/"),
        ("/bluesnews/_18/18_01_27_Harris/", "/photo/2018/2018-01-27-harris/"),
        ("/bluesnews/_18/18_02_24_Shanna/", "/photo/2018/2018-02-24-shanna/"),
        ("/bluesnews/_18/18_03_24_Guy_Davis/", "/photo/2018/2018-03-24-guy-davis/"),
        ("/bluesnews/_18/18_11_11_Mark_Hummel/", "/photo/2018/2018-11-11-mark-hummel/"),
        ("/bluesnews/_18/19_01_22_Shinel/", "/photo/2019/2019-01-22-shinel/"),
        ("/bluesnews/_19/19_01_31_JJThames/", "/photo/2019/2019-01-31-jjthames/"),
        ("/bluesnews/_19/19_03_04_Nekrasov_I/", "/photo/2019/2019-03-04-nekrasov-i/"),
        ("/bluesnews/_19/19_04_28_Kolosova/", "/photo/2019/2019-04-28-kolosova/"),
        ("/bluesnews/_19/19_11_10_Crosseyedcats/", "/photo/2019/2019-11-10-crosseyedcats/"),
        ("/bluesnews/_19/2019-11-24_Juk_Kozh/", "/photo/2019/2019-11-24-juk-kozh/"),
        ("/bluesnews/_19/Arkh19_Guitar/", "/photo/2019/2019-arkh19-guitar/"),
        ("/bluesnews/_22/", "/photo/2022/2022-11-23-neighbours/"),
    ]
    # NOTE: subdir/* dynamic rules moved to _middleware.js (bluesnews map)
    for src, tgt in bluesnews_redirects:
        lines.append(f"{src}  {tgt}  301")
    lines.append("")
    lines.append("# Gallery per-photo HTM pages → parent gallery index")
    lines.append("# Old gallery tools generated one .htm per photo; replaced by generated index.html")
    lines.append("/bluesnews/*/*.htm  /bluesnews/*/  301")
    lines.append("/bluesnews/*/*/*.htm  /bluesnews/*/*/  301")
    lines.append("/bluesnews/*/*/*/*.htm  /bluesnews/*/*/*/  301")
    lines.append("")

    OUT_REDIRECTS.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  _redirects: {len([l for l in lines if l and not l.startswith('#')])} rules")

    # ── Cloudflare notes ──────────────────────────────────────────────────────
    cf_notes = """\
# Cloudflare Pages redirect notes
# The _redirects file contains all albumview and artistview redirects
# using query-string matching (one line per ID).
#
# Cloudflare Pages supports ?param=value matching in _redirects since 2023.
# If this does not work on your plan, use Cloudflare Bulk Redirect Lists:
#   - Import albumview-redirects.csv for albumview.aspx?cdid=N redirects
#   - Import artistview-redirects.csv for artistview.aspx?aid=N redirects
#
# /forum/?tid=N → /forum/topic-N/ is handled by serve.py locally.
# In production, set up a Cloudflare Transform Rule:
#   Match: URI path = /forum/ AND query string contains tid
#   Action: Redirect to /forum/topic-{tid}.html
"""
    OUT_CF_NOTES.write_text(cf_notes, encoding="utf-8")

    # ── Bulk redirect CSV files ───────────────────────────────────────────────
    base = "https://blues.ru"

    csv_lines = ["source_url,target_url,status_code,preserve_query_string"]
    for album_id in sorted(albums.keys()):
        review_slug = review_by_album.get(album_id)
        if review_slug:
            target = f"{base}/review/{review_slug}/"
        else:
            target = f"{base}/review/"
        csv_lines.append(f"{base}/data/albumview.aspx?cdid={album_id},{target},301,false")
    csv_path = ARC / "albumview-redirects.csv"
    csv_path.write_text("\n".join(csv_lines) + "\n", encoding="utf-8")
    print(f"  albumview-redirects.csv: {len(csv_lines)-1} entries")

    csv2_lines = ["source_url,target_url,status_code,preserve_query_string"]
    for artist_id in sorted(artists.keys()):
        artist = artists[artist_id]
        slug = artist.get("slug", "")
        legacy_dir = legacy_dir_for_artist(artist)
        if slug:
            target = f"{base}/artist/{slug}/"
        elif legacy_dir:
            target = f"{base}/artist/{legacy_dir}/"
        else:
            target = f"{base}/artist/"
        csv2_lines.append(f"{base}/data/artistview.aspx?aid={artist_id},{target},301,false")
    csv2_path = ARC / "artistview-redirects.csv"
    csv2_path.write_text("\n".join(csv2_lines) + "\n", encoding="utf-8")
    print(f"  artistview-redirects.csv: {len(csv2_lines)-1} entries")

    print("  cloudflare-rules.txt: notes written")


if __name__ == "__main__":
    main()
