#!/usr/bin/env python3
"""
Generate _redirects file for Cloudflare Pages.

Legacy URL patterns on blues.ru:
  /data/albumview.aspx?cdid=N  → /review/{slug}/
  /data/artistview.aspx?aid=N  → /artist/{legacy_dir}/

Cloudflare Pages _redirects supports one-line-per-URL query string matching
using the format: /path?param=value  /target  301
We generate one line per album/artist ID.

Also generates:
  albumview-redirects.csv  — Cloudflare bulk redirect CSV (same data)
  artistview-redirects.csv — Cloudflare bulk redirect CSV (same data)
  cloudflare-rules.txt     — notes for transforms that need dashboard config

Run from /Users/fedor/bluesru/
"""

import yaml
import re
from pathlib import Path

import os
ARC = Path(__file__).resolve().parent.parent
DATA = ARC / "data"
ALBUMS_DIR = DATA / "albums"
ARTISTS_YAML = DATA / "artists.yaml"
REVIEWS_DIR = DATA / "blues-data" / "reviews"  # unused, kept for fallback
OUT_REDIRECTS = ARC / "_redirects"
OUT_CF_NOTES = ARC / "cloudflare-rules.txt"


def load_albums():
    """Return dict: album_id → album dict."""
    albums = {}
    for p in ALBUMS_DIR.glob("*/*.yaml"):
        a = yaml.safe_load(p.read_text(encoding="utf-8"))
        if a and a.get("id"):
            albums[int(a["id"])] = a
    return albums


def load_review_by_album():
    """Return dict: album_id → review_slug (from embedded reviews in album YAMLs)."""
    review_by_album = {}
    for p in sorted(ALBUMS_DIR.glob("*/*.yaml")):
        album = yaml.safe_load(p.read_text(encoding="utf-8")) or {}
        album_id = album.get("id")
        reviews = album.get("reviews", [])
        if album_id and reviews:
            first_id = reviews[0].get("id", "")
            slug = f"review-{first_id}" if first_id else p.stem
            try:
                review_by_album[int(album_id)] = slug
            except (ValueError, TypeError):
                pass
    # Fallback to old separate review .md files
    if not review_by_album and REVIEWS_DIR.exists():
        for p in sorted(REVIEWS_DIR.glob("review-*.md")):
            text = p.read_text(encoding="utf-8")
            lines = text.split("\n")
            if not lines or lines[0].strip() != "---":
                continue
            meta = {}
            for line in lines[1:]:
                if line.strip() == "---":
                    break
                if ":" in line:
                    k, v = line.split(":", 1)
                    meta[k.strip()] = v.strip().strip("'\"")
            album_id_str = meta.get("album_id", "")
            slug = meta.get("slug", "")
            if album_id_str and slug:
                try:
                    review_by_album[int(album_id_str)] = slug
                except ValueError:
                    pass
    return review_by_album


def load_artists():
    """Return dict: artist_id → artist dict."""
    with open(ARTISTS_YAML, encoding="utf-8") as f:
        artists_list = yaml.safe_load(f)
    return {int(a["id"]): a for a in artists_list}


def legacy_dir_for_artist(artist):
    """Return the legacy bluesmen/ directory name, or '' if none."""
    lp = (artist.get("legacy_path") or "").strip("/")
    parts = lp.split("/")
    ld = parts[-1] if (parts and parts[-1]) else ""
    # Reject external URLs and entries with dots (domain names)
    if "." in ld or ld.startswith("www."):
        return ""
    return ld


def main():
    print("Generating _redirects...")

    albums = load_albums()
    review_by_album = load_review_by_album()
    artists = load_artists()
    lines = []
    lines.append("# Blues.Ru archive _redirects")
    lines.append("# Generated by generate_redirects.py")
    lines.append("")

    # ── Static ASPX page redirects ────────────────────────────────────────────
    lines.append("# Static ASPX page redirects")
    simple_redirects = [
        ("/review/default.aspx", "/review/"),
        ("/review/rss.aspx", "/review/rss.xml"),
        ("/news/default.aspx", "/news/"),
        ("/artist/default.aspx", "/artist/"),
        ("/forum/default.aspx", "/forum/"),
        ("/links/default.aspx", "/links/"),
        ("/club/default.aspx", "/club/"),
        ("/club/team.aspx", "/club/team/"),
        ("/club/tours.aspx", "/club/tours/"),
        ("/calendar/default.aspx", "/calendar/"),
        ("/data/varalbumsview.aspx", "/review/"),
    ]
    for old, new in simple_redirects:
        lines.append(f"{old}  {new}  301")

    # ── Efes section: .asp → .htm redirects ──────────────────────────────────
    lines.append("")
    lines.append("# /efes/*.asp → /efes/*.htm  (server exposed .asp URLs for .htm files)")
    efes_dir = ARC / "content" / "efes"
    if efes_dir.exists():
        for htm in sorted(efes_dir.glob("*.htm")):
            stem = htm.stem
            lines.append(f"/efes/{stem}.asp  /efes/{stem}.htm  301")

    lines.append("")

    # NOTE: /data/albumview.aspx?cdid=N and /data/artistview.aspx?aid=N redirects
    # are NOT in _redirects — CF Pages ignores query strings in _redirects rules.
    # These are handled by _middleware.js using /data/redirects.json (generated
    # at build time by generate_data_json.py).
    lines.append("# albumview.aspx / artistview.aspx → handled by _middleware.js (query-string)")
    lines.append("/data/albumview.aspx  /review/  302")
    lines.append("/data/artistview.aspx  /artist/  302")
    lines.append("")
    album_redirects = []
    artist_redirects = []

    # ── /bluesmen/ → /artist/ (legacy URL rename) ────────────────────────────
    # NOTE: Per-artist /bluesmen/OldDir/* dynamic rules are handled by _middleware.js.
    # Only the root and catch-all go here to stay under CF's 100 dynamic rule limit.
    lines.append("# /bluesmen/ section renamed to /artist/")
    lines.append("/bluesmen/  /artist/  301")
    lines.append("/bluesmen/default.aspx  /artist/  301")
    lines.append("# Catch-all for /bluesmen/ (per-artist slug mapping done in _middleware.js)")
    lines.append("/bluesmen/*  /artist/:splat  301")
    lines.append("")

    # ── news.aspx → /updates/ ────────────────────────────────────────────────
    # NOTE: news.aspx?y=YYYY query-string redirects handled by _middleware.js
    lines.append("# news.aspx (query-string redirect handled by middleware)")
    lines.append("/news.aspx  /updates/  301")
    lines.append("")

    # ── Catch-all for any remaining .aspx URLs ────────────────────────────────
    lines.append("# Catch-all for .aspx files not handled above")
    lines.append("/data/*  /  302")
    lines.append("/*.aspx  /  302")
    lines.append("")

    # ── Old section redirects ─────────────────────────────────────────────────
    lines.append("# Old section redirects")
    lines.append("/cdreview/  /review/  301")
    lines.append("/cdreview/*  /review/:splat  301")
    lines.append("/bluesme/*  /artist/:splat  301")
    lines.append("/zappazuhoi/default.htm  /zappazuhoi/  301")
    lines.append("")
    # Artists whose bluesmen/ TitleCase dirs are NOT in legacy_path (from data file)
    lines.append("# /bluesmen/ TitleCase dirs not in legacy_path (no auto-gen redirect)")
    extra_file = DATA / "bluesmen-extra-redirects.yaml"
    extra_bluesmen = yaml.safe_load(extra_file.read_text(encoding="utf-8")) if extra_file.exists() else {}
    for old_dir, new_slug in (extra_bluesmen or {}).items():
        lines.append(f"/bluesmen/{old_dir}/  /artist/{new_slug}/  301")
        lines.append(f"/bluesmen/{old_dir}/*  /artist/{new_slug}/:splat  301")
    # Artist whose slug differs from what the live site generates from the name
    lines.append("/artist/b-b-the-blues-shacks/  /artist/bb-the-blues-shacks/  301")
    lines.append("/artist/b-b-the-blues-shacks/*  /artist/bb-the-blues-shacks/:splat  301")
    lines.append("")
    lines.append("# /label/ TitleCase → lowercase (live site used TitleCase dirs)")
    lines.append("# /reading/ → /article/ (content consolidated into article/)")
    lines.append("/reading/  /article/  301")
    lines.append("/reading/wolf_palmer1.htm  /article/howling-wolf-deep-blues-1.html  301")
    lines.append("/reading/wolf_palmer2.htm  /article/howling-wolf-deep-blues-2.html  301")
    lines.append("/reading/RP01.htm  /article/robert-palmer-muddy-waters.html  301")
    lines.append("/reading/MuddyGordon1.htm  /article/muddy-waters-library-of-congress.html  301")
    lines.append("/reading/LB10/Living_blues.htm  /article/living-blues-veterans.html  301")
    lines.append("/reading/*  /article/  302")
    lines.append("")
    lines.append("# /label/ TitleCase → lowercase (live site used TitleCase dirs)")
    lines.append("/label/Alligator/  /label/alligator/  301")
    lines.append("/label/Alligator/*  /label/alligator/:splat  301")
    lines.append("/label/Blues_Leaf/  /label/blues-leaf/  301")
    lines.append("/label/Blues_Leaf/*  /label/blues-leaf/:splat  301")
    lines.append("/label/Chess/  /label/chess/  301")
    lines.append("/label/Chess/*  /label/chess/:splat  301")
    lines.append("")
    lines.append("# News archive redirects")
    lines.append("/news/archive/:year/  /news/:year/  301")
    lines.append("/news/archive/  /news/2024/  301")
    lines.append("")
    # ── bluesnews _13–_22 subdir → photo gallery redirects ───────────────────
    # Loaded from data/bluesnews-redirects.yaml; matched by JPG filename overlap.
    lines.append("# bluesnews/_NN/subdir → /photo/ gallery redirects (matched by JPG filenames)")
    bn_file = DATA / "bluesnews-redirects.yaml"
    bn_raw = yaml.safe_load(bn_file.read_text(encoding="utf-8")) if bn_file.exists() else {}
    # Normalize: keys may lack trailing slash; add it for _redirects format
    bluesnews_redirects = [
        (k.rstrip("/") + "/", v) for k, v in (bn_raw or {}).items()
    ]
    # NOTE: subdir/* dynamic rules moved to _middleware.js (bluesnews map)
    for src, tgt in bluesnews_redirects:
        lines.append(f"{src}  {tgt}  301")
    lines.append("")
    lines.append("# Gallery per-photo HTM pages → parent gallery index")
    lines.append("# Old gallery tools generated one .htm per photo; replaced by generated index.html")
    lines.append("/bluesnews/*/*.htm  /bluesnews/*/  301")
    lines.append("/bluesnews/*/*/*.htm  /bluesnews/*/*/  301")
    lines.append("/bluesnews/*/*/*/*.htm  /bluesnews/*/*/*/  301")
    lines.append("")

    OUT_REDIRECTS.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"  _redirects: {len([l for l in lines if l and not l.startswith('#')])} rules")

    # ── Cloudflare notes ──────────────────────────────────────────────────────
    cf_notes = """\
# Cloudflare Pages redirect notes
# The _redirects file contains all albumview and artistview redirects
# using query-string matching (one line per ID).
#
# Cloudflare Pages supports ?param=value matching in _redirects since 2023.
# If this does not work on your plan, use Cloudflare Bulk Redirect Lists:
#   - Import albumview-redirects.csv for albumview.aspx?cdid=N redirects
#   - Import artistview-redirects.csv for artistview.aspx?aid=N redirects
#
# /forum/?tid=N → /forum/topic-N/ is handled by serve.py locally.
# In production, set up a Cloudflare Transform Rule:
#   Match: URI path = /forum/ AND query string contains tid
#   Action: Redirect to /forum/topic-{tid}.html
"""
    OUT_CF_NOTES.write_text(cf_notes, encoding="utf-8")

    # ── Bulk redirect CSV files ───────────────────────────────────────────────
    base = "https://blues.ru"

    csv_lines = ["source_url,target_url,status_code,preserve_query_string"]
    for album_id in sorted(albums.keys()):
        review_slug = review_by_album.get(album_id)
        if review_slug:
            target = f"{base}/review/{review_slug}/"
        else:
            target = f"{base}/review/"
        csv_lines.append(f"{base}/data/albumview.aspx?cdid={album_id},{target},301,false")
    csv_path = ARC / "albumview-redirects.csv"
    csv_path.write_text("\n".join(csv_lines) + "\n", encoding="utf-8")
    print(f"  albumview-redirects.csv: {len(csv_lines)-1} entries")

    csv2_lines = ["source_url,target_url,status_code,preserve_query_string"]
    for artist_id in sorted(artists.keys()):
        artist = artists[artist_id]
        slug = artist.get("slug", "")
        legacy_dir = legacy_dir_for_artist(artist)
        if slug:
            target = f"{base}/artist/{slug}/"
        elif legacy_dir:
            target = f"{base}/artist/{legacy_dir}/"
        else:
            target = f"{base}/artist/"
        csv2_lines.append(f"{base}/data/artistview.aspx?aid={artist_id},{target},301,false")
    csv2_path = ARC / "artistview-redirects.csv"
    csv2_path.write_text("\n".join(csv2_lines) + "\n", encoding="utf-8")
    print(f"  artistview-redirects.csv: {len(csv2_lines)-1} entries")

    print("  cloudflare-rules.txt: notes written")


if __name__ == "__main__":
    main()
