<p class="right">


<font color="#FF0000">02.12.03.</font>
В разделе <a href="music.htm">Музыка</a> выложено 6 композиций
с альбомов <a href="HeavySteppin.htm">Heavy Steppin'</a> и
<a href="Troublemaker.htm">Troublemaker</a>.<br />

<font color="#FF0000">26.11.03.</font>
Со 2-го по 6-го декабря 2003 г. пройдут гастроли Регтайма по поводу
выхода диска. 4-го декабря презентация в клубе Форте.<br />

<font color="#FF0000">26.11.03.</font>
Вышел второй диск группы под названием <a href="Troublemaker.htm">Troublemaker</a>!<br />

<font color="#FF0000">21.10.02-26.11.03.</font>
Новостей было много, но на сайте они, увы, не обновлялись...<br />

<font color="#FF0000">21.10.02.</font>
С 31 октября по 9 ноября в Москве пройдут осенние гастроли Регтайма.<br />
                  
<font color="#FF0000">27.04.02.</font>
В Москве и во Владимире начинаются большие гастроли Регтайма, приуроченные к выходу
в свет первого диска группы.<br />

<font color="#FF0000">26.04.02.</font>
На лейбле Dialog Music вышел дебютный CD группы под названием Heavy Steppin'!<br />

<font color="#FF0000">15.01.02.</font>
24 и 26 января состоятся два концерта в московских клубах Б.Б.Кинг и Форте<br />

<font color="#FF0000">19.10.01.</font>
С 1 по 15 ноября пройдут первые <a href="gigs.htm">гастроли группы в 
Москве</a>! За две недели состоится 6 концертов, в том числе, джем
в клубе БиБиКинг.<br />

<font color="#FF0000">08.10.01.</font>
В разделе <a href="music.htm">музыка</a> появились новые записи песен
<a href="music.htm">Boogie Boy, Heavy Steppin', I Can't Dance</a>,
написанных Арсеном Шомаховым<br />

<font color="#FF0000">14.09.01.</font> 
<a href="review.htm">Отзыв</a> Ф.Романенко о группе<br />

<font color="#FF0000">14.09.01.</font> 
<a href="interview.htm">Интервью</a> с Арсеном Шомаховым<br />

<font color="#FF0000">14.07.01.</font> 
&quot;Регтайм&quot; приняли участие в первом фолк-блюз фестивале
<a href="http://www.nevadelta.spb.ru/" target="_blank">&quot;Дельта Невы&quot;</a><br />

<font color="#FF0000">03.06.01.</font> 
Открылся официальный сайт группы &quot;Регтайм&quot;.<br />

<font color="#FF0000">25.05.01.</font> 
Группа &quot;Регтайм&quot; вошла в список &quot;Российские исполнители&quot; 
сайта <a href="http://blues.ru/" target="_blank">&quot;Блюз.Ру&quot;</a><br />

</p>
