<h2 align="center">Поддержите Blues.Ru</h2>
<p align="center">Мы оплачиваем AI для разработки сайта и обработки информации, а также хостинг.</p>

<table border="0" cellpadding="0" cellspacing="8" align="center"><tr valign="middle">
<td><b style="font-size: 150%;">&dollar;</b></td>
<td>
<form action="https://www.paypal.com/donate" method="post" target="_top" style="margin:0">
<input type="hidden" name="hosted_button_id" value="RU4P9RGPB58Q8">
<input type="image" src="/images/paypal-donate-now.png" width="160" height="49" border="0" name="submit" alt="Donate via PayPal">
</form>
</td>
<td style="width: 10px;"></td>
<td>
<a href="https://boosty.to/blues.ru/donate">
<img src="/images/boosty-donate.svg" width="269" height="43" alt="Donate: Boosty" border="0"></a>
</td>
<td><b style="font-size: 150%;">&#8381;</b></td>
</tr></table>
