<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8>
<title><%=sTitle%></title>
<link rel="stylesheet" type="text/css" href="/nbf/style.css">
<% if (!String.IsNullOrEmpty((String)Context.Items["CustomCss"])) { %>
<link rel="stylesheet" type="text/css" href="/nbf/<%=Context.Items["CustomCss"]%>">
<% } %>
</head>

<body bgcolor="#FFFFFF" text="#000000" link="#0000FF" vlink="#5511CC" alink="#00BB00" background="/nbf/images/nbftextr.gif">

<table border="0" cellpadding="0" cellspacing="6">
  <tr>
    <td width="150" valign="top" align="center">
<a href="/nbf/">
<img border="0" src="/nbf/images/menulogo.gif" align="center" hspace="4" alt="Notodden Blues Festival.">
</a>
    </td>
    <td width="1" bgcolor="black"></td>
    <td valign="center">

<h1 align="center"><font color="#0000FF"><%=sTitle%></font></h1>

</td>
  </tr>
<tr><td height="1" bgcolor="black" colspan="3"></td></tr>
  <tr>
    <td width="200" valign="top">


<p>
  <b>2011: 24th NBF</b> <small><i>(4.08-7.08)</i></small>
  <ul>
    <li>
      <small><a href="/nbf/nbf11.htm">24-й Notodden Blues Festival 2011.</a><br>
       <i>Статья Федора Романенко.</i><br></small>
    </li>
  </ul>
</p>

<p>
  <b>2005: 18th NBF</b> <small><i>(4.08-7.08)</i></small>
  <ul>
    <li>
      <small><a href="/nbf/nbf05pr.htm">18-й Notodden Blues Festival 2005.</a><br>
       <i>Официальный пресс-релиз фестиваля.</i><br></small>
    </li>
  </ul>
</p>


<p>
  <b>2004: 17th NBF</b> <small><i>(5.08-8.08)</i></small>
  <ul>
    <li>
      <small><a href="/nbf/nbf04.htm">Notodden Blues Festival 2004. Блюз через край.</a><br>
       <i>Статья Ф.Романенко</i><br></small>
    </li>
    <li>
      <small><a href="/nbf/nbf04vr.htm">Горячий норвежский фестиваль Notodden Bluesfest 2004.</a><br>
       <i>Статья В.Русинова</i><br></small>
    </li>
    <li>
      <small><a href="/nbf/nbf04f.htm">The Ballad Of Notodden.</a><br>
       <i>Статья С.Фунтусовой</i><br></small>
    </li>
    <li><small><a href="/photo/2004/nbf-2004/">Фотогалерея (Photos)</a></small></li>
    <li><small><a href="http://www.bluescats.ru/files/notodden2004/">Фотографии М.Лернер</a></small></li>
  </ul>
</p>


<p>
  <b>2003: 16th NBF</b> <small><i>(31.07-3.08)</i></small>
  <ul>
    <li>
      <small><a href="/nbf/nbf03.htm">Отчет о Notodden Blues Festival 2003. Russians are here!</a><br>
       <i>Статья Ф.Романенко</i><br></small>
    </li>
    <li><small><a href="/photo/2003/nbf-2003/">Фотогалерея (Photos)</a></small></li>
  </ul>
</p>

<p>
  <b>2002: 15th NBF</b> <small><i>(1.08-4.08)</i></small>
  <ul>
    <li>
      <small><a href="/nbf/nbf02.htm">Notodden Blues Festival 2002 - блюзовый праздник</a><br>
       <i>Статья Ф.Романенко</i><br></small>
    </li>
    <li><small><a href="/photo/2002/nbf-2002/">Фотогалерея (Photos)</a></small></li>
  </ul>
</p>

<p>
  <b>2001: 14th NBF</b> <small><i>(2.08-5.08)</i></small>
  <ul>
    <li>
      <small><a href="/nbf/nbf01.htm">Чем норвежский городок Нутодден обязан Америке?</a><br>
       <i>Статья А.Евдокимова</i><br></small>
    </li>
    <li><small><a href="/photo/2001/nbf-2001/">Фотогалерея (Photos)</a></small></li>
  </ul>
</p>

<p>
  <b>1999: 12th NBF</b> <small><i>(12.08-15.08)</i></small>
  <ul>
    <li><small><a href="/photo/1999/nbf-1999/">Фотогалерея (Photos)</a></small></li>
  </ul>
</p>

<p>
  <b>1998: 11th NBF</b> <i><small>(6.08-9.08)</small></i>

  <ul>
    <li>
      <small><a href="/nbf/nbf98.htm">Впечатления от фестиваля</a><br>
        <i>Статья Ф.Романенко</i></small><br>
    </li>
    <li><small><a href="/photo/1998/nbf-1998/">Фотогалерея (Photos)</a></small></li>
  </ul>
</p>


<p>
  <small><a href="/nbf/nbfhowto.htm">Как съездить в Нотодден? Руководство.</a><br>
   <i>Федор Романенко</i><br></small>
</p>

<p>
  <small><a href="/nbf/nbfabout.htm">Блюз там, где вы меньше всего его ожидаете.</a><br>
   <i>Статья Кнута Слеттемо</i><br></small>
</p>

<p><b><a href="/photo/2004/nbf-2004/">Фотогалерея (Photos)</a></b></p>

<p><b><a href="http://www.bluesfest.no">www.bluesfest.no</a></b><br>
<small>официальный сайт фестиваля.</small></p>

<p><b><a href="/">Блюз в России</a></b></p>


    </td>
    <td width="1" bgcolor="black"></td>
    <td valign="top">
