<table align="center" border="0" cellspacing="2">
<tr><td rowspan="2"><a href="/band/Mississippi2/"><img src="/band/Mississippi2/CD_Mississippi2.gif" width="200" height="200" hspace="10" align="left" alt="Я не увижу Миссиссиппи - 2" border="0"></a></td>
<td align="center">
<small><b>Автозвук</small><br>
<a href="http://www.avtozvuk.com/"><img src="/band/Mississippi2/avtozvuk0410.jpg" alt="Автозвук, номер 10/2004"></a>
</td>
</tr>
<tr><td align="center">
<small><b>Салон<br>Audio Video</b></small><br>
<a href="http://www.salonav.com"><img src="/band/Mississippi2/salonav0410.jpg" alt="Салон Audio Video, номер 10/2004"></a>
</td>
</tr>
</table>
<p>Второй сборник российского блюза <a href="/band/Mississippi2/"><b>"Я не увижу Миссиссиппи - 2"</b></a>, созданный
при участии сайта <b>blues.ru</b>, выходит как приложение к октябрьским
номерам журналов <a href="http://www.avtozvuk.com/"><b>Автозвук</b></a> и 
<a href="http://www.salonav.com"><b>Салон Audio Video</b></a>. Журналы
с диском уже сейчас можно купить в киосках Союзпечати и супермаркетах.</p>


